dataset:
  path: "C:/PlantVillage"
  image_size: 224
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15

training:
  model: "resnet50"
  epochs: 25
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  num_workers: 0

augmentation:
  horizontal_flip: true
  rotation_degrees: 15
  random_crop_scale: [0.8, 1.0]
  
normalization:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
